"""Updated User and Badge models to fix backref conflict

Revision ID: 6e6f57f7f6f0
Revises: ca6b116f1e92
Create Date: 2025-05-09 12:13:07.964975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6f57f7f6f0'
down_revision = 'ca6b116f1e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('token')
    )
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('follower', sa.String(), nullable=False),
    sa.Column('followed', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['followed'], ['users.username'], ),
    sa.ForeignKeyConstraint(['follower'], ['users.username'], ),
    sa.PrimaryKeyConstraint('follower', 'followed')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('postponed', sa.Boolean(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('second', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.username'], ),
    sa.ForeignKeyConstraint(['second'], ['users.username'], ),
    sa.ForeignKeyConstraint(['winner'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('commenter', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['commenter'], ['users.username'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('flagger', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['flagger'], ['users.username'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('liker', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['liker'], ['users.username'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('voter', sa.String(), nullable=False),
    sa.Column('candidate', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['voter'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('likes')
    op.drop_table('flags')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_table('badges')
    op.drop_table('users')
    # ### end Alembic commands ###
