name: Run E2E Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Avvia i servizi con Docker Compose
      run: docker compose up -d --build

    - name: Attendi che Flask sia pronto
      run: |
        echo "Aspetto che il server Flask risponda..."
        for i in {1..10}; do
          curl -s http://localhost:5000/status/test || true
          if curl -s http://localhost:5000/status/test | grep -q '"data"'; then
            echo "Flask è pronto!"
            break
          fi
          sleep 3
        done

    - name: Esegui i test E2E
      run: docker compose exec -T web pytest tests_e2e
