name: Run E2E Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker-compose up -d --build

    - name: Wait for Flask
      run: |
        echo "Waiting for Flask to start..."
        for i in {1..10}; do
          curl -s http://localhost:5000/status/test || true
          if curl -s http://localhost:5000/status/test | grep -q '"data"'; then
            echo "Server is up!"
            break
          fi
          sleep 3
        done

    - name: Run tests
      run: docker-compose exec -T web pytest tests_e2e
